name: unitests
on:
  [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: cmake
              uses: lukka/get-cmake@latest

            - name: Run.
              run: ./make tests